# Regression: Simple Linear  
Dataset : diabetes.csv 
<h4>Apply Data pre-processing (Label Encoding , Data Transformation....) 
techniques if necessary. 
Use any one feature of the dataset to train and test the regression model.</h4>

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [19]:
df = pd.read_csv("/Users/namanlabhsetwar/Desktop/Sem 5 Practical/ML- Lab Assignments/LP-1 Dataset/Regression/1.01. Simple linear regression.csv")

In [20]:
df.head(10)

SAT   GPA
0  1714  2.40
1  1664  2.52
2  1760  2.54
3  1685  2.74
4  1693  2.83
5  1670  2.91
6  1764  3.00
7  1764  3.00
8  1792  3.01
9  1850  3.01

In [21]:
df.isnull().sum()

SAT    0
GPA    0
dtype: int64

In [22]:
# Select the feature and target
x = df['SAT'].values.reshape(-1, 1)  # Feature (reshape for scikit-learn)
y = df[['GPA']].values  # Target (reshape for scikit-learn)


In [23]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


In [24]:
# Create a linear regression model
model = LinearRegression()

# Fit the model to the training data
model.fit(x_train, y_train)


LinearRegression()

In [25]:
y_pred = model.predict(x_test)

In [26]:
model.predict([[1700]])

array([[3.12264734]])

In [27]:
print(y_pred)

[[3.46632244]
 [3.1432091 ]
 [3.2416118 ]
 [3.06830555]
 [3.17405174]
 [3.46485374]
 [3.17405174]
 [3.33120231]
 [3.11236646]
 [3.31651534]
 [3.36498234]
 [3.49863377]
 [3.34148319]
 [3.54416338]
 [3.39729368]
 [3.3855441 ]
 [3.35029538]]


In [28]:
print(x_train.shape)
print(x_test.shape)

(67, 1)
(17, 1)


In [29]:
print(x_train)

[[1997]
 [1966]
 [1979]
 [1775]
 [1769]
 [1831]
 [2020]
 [1850]
 [1861]
 [1670]
 [1925]
 [1934]
 [1880]
 [1990]
 [2050]
 [1755]
 [1893]
 [1764]
 [1934]
 [1730]
 [1786]
 [1931]
 [1826]
 [1634]
 [1712]
 [1893]
 [1685]
 [1674]
 [1777]
 [1792]
 [1850]
 [1764]
 [1808]
 [2015]
 [1808]
 [1802]
 [1824]
 [1962]
 [1872]
 [1821]
 [1850]
 [1787]
 [1857]
 [1974]
 [1702]
 [1810]
 [2020]
 [1953]
 [1775]
 [1936]
 [1891]
 [2041]
 [1975]
 [1954]
 [1794]
 [1664]
 [1907]
 [1722]
 [1760]
 [1687]
 [1843]
 [2021]
 [1761]
 [1964]
 [1778]
 [1773]
 [1855]]


In [30]:
print(x_test)

[[1934]
 [1714]
 [1781]
 [1663]
 [1735]
 [1933]
 [1735]
 [1842]
 [1693]
 [1832]
 [1865]
 [1956]
 [1849]
 [1987]
 [1887]
 [1879]
 [1855]]


In [31]:
# scaler = StandardScaler()
# X_train_scaled = scaler.fit_transform(x_train)
# X_test_scaled = scaler.transform(x_test)

<h4> FORMULAS IMPORTANT TO LEARN</h4>

In [32]:
# Coefficients
coefficients = model.coef_[0]
intercept = model.intercept_

# Residual sum of squares
rss = ((y_test - model.predict(x_test)) ** 2).sum()

# Coefficient of determination (R^2)
r2 = model.score(x_test, y_test)
print("ANSWER")

print('**************************************************************')
print(f'Coefficients: {coefficients}')
print(f'Intercept: {intercept}')
print(f'Residual Sum of Squares: {rss}')
print(f'Coefficient of Determination (R^2): {r2}')
print('**************************************************************')



ANSWER
**************************************************************
Coefficients: [0.0014687]
Intercept: [0.62586247]
Residual Sum of Squares: 0.8922637458581333
Coefficient of Determination (R^2): 0.46949246374602116
**************************************************************


In [34]:
plt.scatter(x_test, y_test, color='blue', label='Actual Data')

# Plot the regression line
plt.plot(x_test, y_pred, color='red', linewidth=3, label='Regression Line')

# Add labels and a legend
plt.xlabel('SAT')
plt.ylabel('GPA')
plt.title('Simple Linear Regression Visualization')
plt.legend()

# Display the plot
plt.show()